In [108]:
def factorial(n):
    n_sum = 0
    for i in range(n + 1):
        n_sum += i
    return n_sum


res = 0
for i in range(11):
    res += factorial(i)

print(res)

220


In [109]:
import random
import numpy as np

s = []
for n in range(16):
    s.append(random.randint(10, 50))

#转化为矩阵
a = np.asarray(s)
a = a.reshape(4, 4)
print("转化结果为:")
print(a)

print("第1、2行中第0、2、3列的元素:")
for i in [1, 2]:
    for j in [0, 2, 3]:
        print(a[i][j], end=' ')
    print()

s = list(set(s))
s.sort()
s[-1] = 100

print("排序结果为:")
for i in s:
    print(i, end=' ')


转化结果为:
[[11 11 46 24]
 [47 21 23 24]
 [44 43 43 17]
 [14 11 38 47]]
第1、2行中第0、2、3列的元素:
47 23 24 
44 43 17 
排序结果为:
11 14 17 21 23 24 38 43 44 46 100 

In [110]:
import numpy as np

a = np.random.randint(10, 99, 6 * 8)
a = a.reshape(6, 8)

np.savetxt("hw1.txt", a)
print("导入数据:")
print(np.loadtxt("hw1.txt"))

导入数据:
[[77. 81. 39. 84. 70. 82. 45. 78.]
 [80. 34. 45. 58. 31. 79. 73. 24.]
 [52. 26. 46. 46. 76. 69. 63. 30.]
 [32. 48. 16. 66. 44. 96. 70. 10.]
 [70. 75. 57. 11. 98. 62. 65. 95.]
 [61. 42. 37. 84. 54. 92. 29. 35.]]


In [111]:
import numpy as np

a = np.arange(1, 20 + 1, 1)
a = a.reshape(4, 5)

print("按横轴求和结果为:")
print(np.sum(a, axis=1))

print("按纵轴求标准差结果为:")
print(np.std(a, axis=0))

print("求每行平均数为:")
print(np.mean(a, axis=1))

按横轴求和结果为:
[15 40 65 90]
按纵轴求标准差结果为:
[5.59016994 5.59016994 5.59016994 5.59016994 5.59016994]
求每行平均数为:
[ 3.  8. 13. 18.]


In [112]:
import numpy as np

#创建全零数组
a=np.zeros(10*10)
a=a.reshape(10,10)

for i in [0,-1]:
    a[i,:]=1
    a[:,i]=1

#更改后结果
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
